version: '2'
services:
  kue-ui:
    build: .
    restart: always
    environment:
      - DEBUG=*
      - REDIS_HOST=redis
    links:
      - redis
    ports:
      - 3000:3000
  redis:
    image: 'redis:4.0.6-alpine'
    restart: always
